---
title: "Stat 11 Proposed Calendar"
author: "Prof. Suzy Thornton"
date: "Fall 2023"
lang: "en-US"
output:
  html_document:
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---



We will cover three different, but related, units in this one-semester course. These units roughly correspond to the first six parts of your textbook. The units are broken into the following subject areas:


**Unit 1**

- Exploring and understanding data 
- Exploring and understanding relationships between variables 



**Unit 2**

- Collecting data 
- Randomness and probability


**Unit 3**

- Statistical inference from a single sample of data 
- Statistical inference from multiple samples of data 
- Statistical inference for related variables 

<br><br>

**Office Hours** 

Held in SCI 136 on **W F 10:20am-11:20am** or virtually by appointment (see the syllabus for details).

<br><br>

<span style="color:blue">Please understand that this calendar is subject to change depending on the discretion of your professor. Check back regularly for updates.</span>.

<br><br>

In the calendar below **RCHW** corresponds to reading comprehension homework assignments and **PHW** corresponds to project homework assignments.

|Week |Date |Unit |Topics |Reading and homework assignments and assessment items |
|:--- |:--- |:--- |:--- |:--- |
| 1 | Sept 5 | 1 | Visualizing and summarizing data | Part 1: Ch 1-3 <br> RCHW 1+2 |
| 2 | Sept 11 | 1 |  Describing distributions with variability  | Part 1: Ch 4-5 <br> RCHW 3+4  |
| 3 | Sept 18 | 1 |  Describing relationships between two numeric variables | Part 2: Ch 6 <br> PHW 1 |
| 4 | Sept 25 | 1   | Unit 1 topics | Part 2: Ch 7, Ch 8.1-8.3 <br> PHW 2  |
| 5 | Oct 2 | 1, 2  | Collecting data from experiments and observational studies | **Quiz 1** <br> Part 3: Ch 10-11  |
| 6 | Oct 9 | 2 |  Collecting data from experiments and observational studies <br> From randomness to probability and the laws of probability |  Part 3: Ch 10-11 <br> Part 4: Ch 12-13  <br> RCHW 5+6 |
| 7 | Oct 16 |  | Fall Break |   |
| 8 | Oct 23 | 2 |  From randomness to probability and the laws of probability  | Part 4: Ch 14  <br> PHW 3 <br> RCHW 7 |
| 9 | Oct 30 | 2 |  Random variables and probability models | Part 4: Ch 15.1, 15.3, 15.4, 15.5 <br> RCHW 8, 9, 10 |
| 10 | Nov 6 | 2 | Unit 2 topics | **Quiz 2** |
| 11 | Nov 13 | 3 |  Sampling distributions and confidence intervals for a proportion and for a mean |  **Final project proposal** <br> Part 5: Ch 16-17 (except 17.4) <br> RCHW 11+12 |
| 12 | Nov 20 | 3 | Hypothesis tests about a proportion or a mean  | Part 5: Ch 18-19 <br> PHW 4   |
| 13 | Nov 27 | 3 | Comparing grouped numeric data <br> Comparing grouped categorical data | Part 6: Ch 20-22 <br> PHW 5 <br> RCHW 13  |
| 14 | Dec 4 | 3 | Unit 3 topics  | RCHW 14+15 <br> **Quiz 3**  |
| 15 | Dec 11 | 3 |  Ethical statistical practice |  **Final Project Presentations** |
|  |  Dec 20  | 1-3 |  **Final Exam** |  |




