---
title: "Folllow-up to: In-Class Worksheet"
author: "STAT011 with Prof Suzy"
date: "Week 2: Interpreting Multi-variable Plots"
output:
  html_document: default
---

# Ethical Statistical Aanalyssis: What Not to Do 

Woman’s World magazine has a circulation of over 1.3 million readers.^[Material provvided by the DANA Center for Mathematics Pathways] Page 17 of the January 11, 2021, issue contained the article with the headline and excerpt below: 

## (Bad) Example 1 

**Headline**: Japanese breakthrough lowers dementia risk by 64%. STAY SHARP!”

**Excerpt**: “Good news for chocolate lovers: Sip 2 mugs of hot cocoa daily and a study in The American Journal of Clinical Nutrition found you’ll up your “good” cholesterol by 24%. Researchers credit cocoa compounds called flavonoids with the heart-smart effect. What’s more, Appalachian State University scientists say folks who enjoy 25 grams of dark chocolate (about four squares) daily have better memories and multitasking ability than those who don’t indulge.”

**Source**: https://academic.oup.com/ajcn/article/101/3/538/4569408

<br>
<br>


The same issue of Woman’s World magazine contained another article on page 16 with the following headline and excerpt: 


## (Bad) Example 2 

**Headline**: “Proven! Shower ‘tickle’ fires up virus-fighting cells. Immunity Boost”.

**Excerpt**: ``Linger longer in the shower - Aah, that warm water feels so good. While you’re showering, simply massaging your scalp for 10 minutes heightens your ability to quash invading viruses by as much as 32%, suggests research in Scientific Reports. Explains study co-author Sam Brod, Ph.D., stimulating scalp nerves eases stress and encourages the release of virus-killing immune cells (T cells)."

**Source**: https://www.nature.com/articles/srep10913
