---
title: "Group Homework 3"
author: "STAT011-S23"
date: 'Due: 3/5/23'
output:
  html_document: default
---

# Introduction and Purpose 

You will analyze two data sets in this homework assignment. The first data set contains information about a clinical trial testing treatment for arthritis. This data set consists of $84$ patients who either received a drug or a placebo and who rated the level of improvement in their arthritis symptoms. The drug or placebo label is the first categorical variable of interest, and the level of improvement in symptoms (none, some, or marked) is the second categorical variable of interest. This data set is referenced in Problems 1 -- 3. 

The second data set you will analyze for Problem 4 is the data you saw in the second week of class on the survival of different class passengers aboard the ship Titanic. This data consists of $XX$ passengers who either survived the wreck or died and their status as a passenger in first, second, or third class, or as a crew member of the ship. 

Problem 5 requires no data analysis.

The purpose of this assignment is to ....



# Required Tech 

## Excel 

The skills necessary to complete this assignment in Excel are covered in the following seven videos:

* Excel 2016 with Data Analysis Toolpak Introduction to Excel 2016 with Data Analysis Toolpak (1:52)

* Excel 2016 with Data Analysis Toolpak Introduction to Excel 2016 with Data Analysis Toolpak: Common Procedures (3:08)

* Excel 2016 with Data Analysis Toolpak Descriptive Statistics and Confidence Intervals for a Mean (2:57)

* Excel 2016 with Data Analysis Toolpak Histogram (3:08)


## RStudio

The skills necessary to complete this assignment in RStudio are covered in the following seven videos:

* R Studio Video Introduction to R and RStudio  (1:52)

* R Studio Video Getting Started (3:51)

* R Studio Video Working with Data Objects 1 (3:29)

* R Studio Video Working with Data Objects 2 (5:15)

* R Studio Video Importing Data (4:36)

* R Studio Video Descriptive Statistics (3:33)

* R Studio Video Plotting - Histograms, Bar Charts, Boxplots, Scatterplots (4:08)


# Instructions

If you are analyzing this data in Excel you first need to [download the data set for HW 3](https://github.com/ProfSuzy/Stat11/blob/main/Data/EnvoyAir_flights.txt) from our Stat 11 Github Data page. Do this by right clicking on the link "View Raw" and save the link with the name `XXX.csv`. This may take a few moments as it is a large data set.

If you are analyzing this data in RStudio, you will import the data with the following command
```{r, eval=FALSE}
EnvoyAir_flights <- read.delim(
        "https://raw.githubusercontent.com/ProfSuzy/Stat11/main/Data/EnvoyAir_flights.txt",
        sep=",")
```
This may take a few moments as it is a large data set. The data object is called `XXX`. 

Once you have access to the data set, complete all parts of the XX problems in this assignment. You are encouraged to work with your classmates on this assignment but you must hand in your own, unique write up of the solutions. In a Word document, clearly label each problem's solution. Most solutions will include graphics which can be copied from Excel or RStudio and pasted into your solution document. All solutions require a written component. When you are ready to submit your assignment, save the Word document as a PDF and upload it to the Moodle link for Group Homework \#3.


# Problem 1 

create a frequency table for the 84 patients in this study and create a table of proportions.  

What proportion of the patients received a placebo and had marked improvement?


Of all the patients who received a placebo, what proportion of them saw 

  (a) no improvement;

  (b) some improvement;
  
  (d) marked improvement? 

# Problem 2

Name and describe the kind of bias that might be present if administrators decide that instead of subjecting people to random drug testing they’ll just

a) hold hospital-wide meetings and drug test the employees that attend; or instead

b) offer additional employee discounts for those employees who agree to be drug tested.

# Problem 3

Researchers believe that a new drug called AX319 will help bones heal after children have broken or fractured a bone. The researchers believe that AX319 will work differently on bone breaks than on bone fractures. AX319 will be used in conjunction with traditional casts. To test the impact of AX319 on bone healing, the researchers recruit 18 children with bone breaks and 30 children with bone fractures. Design an appropriate experiment to determine if AX319 will help bones heal.


***

# Problem 4

Independence and Titanic data 


***

# Problem 5

(a) The American Red Cross says that about $45\%$ of the U.S. population has Type O blood, $40\%$ Type A, $11\%$ Type B, and the rest Type AB. Someone volunteers to give blood. Calculate the probability that this donor (1) has Type AB blood, (2) has Type A or Type B blood, and (3) does not have Type O blood. 


(b) Suppose IQ scores tend to follow a $N(100, 16)$ distribution. What is the percent of people that you would expect to have an IQ between 112 and 132? (Hint: RStudio software can compute this percentage for you exactly with a quantile function.)

(c) Consider the made-up probability distribution for a (discrete) random variable X shown in the table below.

| X | 0 | 1 | 2 |
| P(X=x) | 0.2 | 0.4 | 0.4 |

(1) Find the mean and standard deviation of this distribution and (2) Suppose another random variable $Y$ is found by $Y = 3X - 2$. Use the rules for means (or expectations) and variances to find the mean and standard deviation of $Y$. 

