---
title: "Homework 4"
author: "STAT011-S20"
date: 'Due: 2/7/2020'
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(nycflights13)
```

<center>This assignment is due on __Friday__ the 7th by __6:00pm__. You must submit your completed assignment as a single PDF document uploaded on Moodle. You can use LateX, R markdown, Word, and/or handwritten notes for your solutions. For any questions that involve coding in R, you must provide both the code and the requested output. (You can copy and paste code from an R script file into a Word document for example.) Please make sure each problem is clearly labeled and that any handwritten components are easily readable. You are allowed to work with your classmates on this homework assignment but you must disclose the names of anyone you collaborate with at the top of your solutions.</center>

***

# Study interpretation problems

## Problem 1

The article “Even Einstein Struggled: Effects of Learning about Great Scientists’ Struggles on High School Students’ Motivation to Learn Science” by Xiadong Lin-Siegler, Janet N. Ahn, Jondou Chen, Fu-Fen Anny Fang, and Myra Luna-Lucero in Journal of Educational Psychology, Vol 108, No. 3: 314-328 (2016) is posted on Moodle. First read the abstract.

Grading Guidelines:
1 point for each part, be generous

a) Skim from the beginning to the “Method” section. Briefly state the main scientific question that this study aims to answer.

Solution:
The main scientific goal is to measure the effect of a story - either achievement, intellectual struggle, or life struggle - on students’ science class grades.


b) What is the explanatory variable(s)? What is the response variable(s)? Was this an observational study, experiment, or sample survey?

Solution:
Explanatory variable: Story type - either Intellectual Struggle Story (ISS), Life Struggle Story (LSS) or Achievement Story (AS).
Response Variable: Class grades/other performance measures
This was an experiment, since the story that students read were assigned by the researcher

c) Can we tell whether the participants received randomized treatment assignment? How does this impact the conclusions we are allowed to draw?

Solution:
Yes, the ‘Procedure and Study Design’ section tells us that students were randomized
to the ISS, LSS, or AS condition at the student level. The order of scientists was also
randomized. This helps assure us that the difference between the groups was indeed caused by the treatment, not merely associated with the treatment. For instance, if only the classes were randomized to a story condition, any difference found in the study could be caused by a difference in teacher. We avoid this problem through individual-level randomization.

d) Can we tell whether the participants were randomly selected? How does this impact the conclusions that we are allowed to draw?

Solution:
No; it is unclear whether the participating students were randomly selected from the
four schools or whether they volunteered; or whether all students in the four schools
were used for the study. Therefore, we don’t know whether the study’s reported effect
sizes would generalize to other NYC high school students, or (for example) only those
who are willing to volunteer for such a study.

e) No mention is made of blinding in this study. Explain in what way blinding might be possible and why it would be beneficial for the study.

Solution:
Since all students (even the control “AS” group) read a story, the subjects may have
been blinded (although the different titles of the stories suggest they may have been
able to figure out they were getting different “treatments”). This is probably a case of Partial Blinding - the students didn’t know which treatment was considered better.
The treatment administrators/teachers should be blinded - they should not know which
students received which stories - to avoid unconscious biases in science grades.
Such biases may cause confounding and destroy interpretability and the internal validity of the study.


## Problem 2 

Coffee stations in offices often just ask users to leave some money to pay for their coffee, but many people just take coffee without leaving any money. Researchers at Newcastle University replaced the picture of flowers behind the coffee station with a picture of staring eyes. They found that the average contribution per user increased significantly, even though the eyes were not real.

Grading Guidelines:
Two points per part, generous grading

a) Was this a survey, observational study, or experiment? How can you tell?

Solution:
Observational study: participants weren’t assigned to either the “flowers” or “eyes”
treatment; researchers only observed
Also accept “Experiment” if they mention that the researchers changed the picture but
there was no random assignment

b) Identify the explanatory variable and the response variable.

Solution:
Explanatory variable: picture (flowers vs eyes)
Response Variable: Contribution per user

c) What does “increased significantly” mean in a statistical sense?

Solution:
That the difference between the two groups is due to more than random variation


## Problem 3  

Is diet or exercise effective in combating insomnia? Some believe that cutting out desserts can help alleviate the problem, while others recommend exercise. Forty volunteers suffering from insomnia agreed to participate in a month-long test. Half were randomly assigned to a special no-desserts diet; the others continued desserts
as usual. Half of the people in each of these groups were randomly assigned to an exercise program, while the others did not exercise. Those who ate no desserts and engaged in exercise showed the most improvement.

Grading Guidelines:
1 points each, be generous with grading

a) Was this a survey, observational study, or experiment? How can you tell?

Solution:
Experiment: participants were assigned to treatment groups

b) Identify the explanatory variable and the response variable.

Solution:
Explanatory: diet and exercise program
Response: amount of sleep

c) Identify any specific sampling schemes (i.e. stratified, systematic, etc.) or experimental designs (i.e. blocked, blinded, etc.)

Solution:
Randomized to diet, then blocked by diet and assigned to an exercise program

d) What type of conclusion can we draw from this study?

Solution:
Whether desserts or exercise causes an improvement in insomnia. Cannot generalize
to the population since participants were not randomly selected

e) Why didn’t the experimenters just have everyone exercise and see if their ability to sleep improved?

Solution:
To be sure that it was the exercise, and not something else, that improved the sleep

f) What would be the advantages and disadvantages of using 100 subjects instead of 40?

Solution:
Advantages: More precise estimates
Disadvantages: Costs

g) Suppose some of the 40 subjects had maintained a healthy weight, but others were quite overweight. Why might researchers choose to block the subjects by weight level before randomly assigning some of each group to the exercise program?

Solution:
Exercise might be more beneficial for those in the healthy or overweight blocks. Blocking by weight level controls for that difference



# Probability problems

## Problem 4 

The American Red Cross says that about 45% of the U.S. population has Type O blood, 40% Type A, 11% Type B, and the rest Type AB. omeone volunteers to give blood. What is the probability that this donor

a) has Type AB blood?
b) has Type A or Type B?
c) is not Type O?

Solution:
a) 1 - (.45 + .4 + .11) = .04
b) P(A or B) = P(A) + P(B) = .45 + .11 = .56 (blood types are disjoint)
c) 1 - P(O) = 1- .45 = .55


## Problem 5 

Suppose IQ scores follow a $N(100, 16)$ distribution. Using R, calculate the percent of people that you would expect to have IQs that are:

1. over 80
2. under 90
3. between 112 and 132


## Problem 6 

Here is a probability distribution for a random variable X:
X 0 1 2
P(X=x) 0.2 0.4 0.4

Grading Guidelines:
2 points for each of A and B; one for mean and one for variance; all or nothing grading

(a) Find the mean and standard deviation of this distribution

Solution:
E(X) = 0(.2) + 1(.4) + 2(.4) = 1.2
V(X) = (0-1.2)ˆ2.2 + (1-1.2)ˆ2.4 + (2-1.2)ˆ2*.4 = .56
sqrt(X) = sqrt(.56) = .748

(b) Let Y = 3X - 2. Use the rules for means and variances to find the mean and standard deviation of Y

Solution:
E(Y) = E(3X - 2) = 3 E(X) - 2 = 3*(1.2) - 2 = 1.6
V(Y) = V(3X - 2) = 9 V(X) = 9*(.56) = 5.04
Sqrt(Y) = sqrt(5.04) = 2.24
