---
title: "Group Homework 5"
author: "STAT011-S23"
date: 'Due: X/X/23'
output:
  html_document: default
---

# Introduction and Purpose 

The data set you will analyse in this homework..... The purpose of this assignment is ....data set consisting of $X$ variables and $X$ observations. 


# Required Tech 

## Excel 

The skills necessary to complete this assignment in Excel are covered in the following seven videos:

* Excel 2016 with Data Analysis Toolpak Introduction to Excel 2016 with Data Analysis Toolpak (1:52)

* Excel 2016 with Data Analysis Toolpak Introduction to Excel 2016 with Data Analysis Toolpak: Common Procedures (3:08)

* Excel 2016 with Data Analysis Toolpak Descriptive Statistics and Confidence Intervals for a Mean (2:57)

* Excel 2016 with Data Analysis Toolpak Histogram (3:08)


## RStudio

The skills necessary to complete this assignment in RStudio are covered in the following seven videos:

* R Studio Video Introduction to R and RStudio  (1:52)

* R Studio Video Getting Started (3:51)

* R Studio Video Working with Data Objects 1 (3:29)

* R Studio Video Working with Data Objects 2 (5:15)

* R Studio Video Importing Data (4:36)

* R Studio Video Descriptive Statistics (3:33)

* R Studio Video Plotting - Histograms, Bar Charts, Boxplots, Scatterplots (4:08)


# Instructions

If you are analyzing this data in Excel you first need to [download the data set for HW 5](https://github.com/ProfSuzy/Stat11/blob/main/Data/EnvoyAir_flights.txt) from our Stat 11 Github Data page. Do this by right clicking on the link "View Raw" and save the link with the name `XXX.csv`. This may take a few moments as it is a large data set.

If you are analyzing this data in RStudio, you will import the data with the following command
```{r, eval=FALSE}
EnvoyAir_flights <- read.delim(
        "https://raw.githubusercontent.com/ProfSuzy/Stat11/main/Data/EnvoyAir_flights.txt",
        sep=",")
```
This may take a few moments as it is a large data set. The data object is called `XXX`. 

Once you have access to the data set, complete all parts of the XX problems in this assignment. You are encouraged to work with your classmates on this assignment but you must hand in your own, unique write up of the solutions. In a Word document, clearly label each problem's solution. Most solutions will include graphics which can be copied from Excel or RStudio and pasted into your solution document. All solutions require a written component. When you are ready to submit your assignment, save the Word document as a PDF and upload it to the Moodle link for Group Homework \#5.


# Problem 1 