---
title: "Quiz 2 Solutions"
output:
  pdf_document: 
    extra_dependencies: ["amsmath","amssymb","amsfonts"]
---

# 1-10 

| | V1 - dots | V2 - slash | V3 - dash |
| --- | --- | --- | --- |
| 1 | c  | a  | e  |
| 2 | c or d |  b or d |  a or d |
| 3 | d  |  c |   c |
| 4 | b  |  e | c  |
| 5 | e  |  e | e  |
| 6 | b  |  d | c  |
| 7 | a  | b  | e  |
| 8 | b  |  c | d  |
| 9 | d  |  a | b  |
| 10 | b  | e  |  b |

***

# Instructions given about showing work 

"to be eligible for partial credit, your answer must show all of your work and/or explain all of your reasoning" 

# 11 

$$\frac{25+29}{26+16+25+29+16+29}= 0.383$$

or, equivalently, 

$$\frac{\frac{25+29}{16+25+16+16+29+16+26+16+25+29+16+29}}{\frac{26+16+25+29+16+29}{16+25+16+16+29+16+26+16+25+29+16+29}}$$
## Rubric

* 1 - correct 

* 0.5 - credit for attempt

* 0.3 - credit for partial attempt (bare minimum attempt)

* 0 - blank/unanswered 

# 12 


Let $A=$ eat breakfast and $B=$ floss teeth. Then $Pr(A) = 0.57$, $Pr(B)=0.80$, and $Pr(A\text{ and }B) = 0.46$.

Hence, $Pr(A\text{ or }B) = Pr(A) + Pr(B) - Pr(A\text{ and }B) = 0.57 + 0.80 - 0.46 = 0.91$

## Rubric

* 1 - correct 

* 1 - correct but no work shown

* 0.9 - correct work, wrong answer 

* 0.5 - correct answer but incorrect work 

* 0.6 - incorrect because answer assumes independence

* 0.5 - credit for attempt 

* 0.3 - credit for partial attempt 

* 0 - blank/unanswered 


# 13 

Let $A=$ ticket for speeding and $B=$ ticket for running red light. Then $Pr(A\text{ and }B) = 0.04$, $Pr(A)=0.12$, and $Pr(B) = 0.09$.

Since $Pr(A \text{ and } B^C) + Pr(A \text{ and }B) = Pr(A)$, we have that $Pr(A\text{ and }B^C) = 0.12 -0.04 =0.08$.

## Rubric

* 1 - correct 

* 0.9 - correct work, wrong answer 

* 0.7 - partially correct work

* 0.5 - correct answer but incorrect work 

* 0.3 - credit for partial attempt 

* 0 - blank/unanswered 


# 14 

Assuming independence means either: 

$$Pr(\text{Yes HD} \mid \text{Yes Mu})= Pr(\text{Yes HD})$$
i.e.$\frac{x}{30} = \frac{80}{120}$ meaning $x=20$, or, equivalently 

$$Pr(\text{Yes HD and Yes Mu}) = Pr(\text{Yes HD})Pr(\text{YesMu})$$
i.e. $\frac{x}{120} = \frac{30}{120} \cdot \frac{80}{120}$ meaning $x=20$. 

## Rubric

* 1 - correct 

* 1 - correct answer, unclear work 

* 0.5 - correct answer, incorrect work 

* 0.1 - incorrect and no work shown 

* 0.3 - incorrect and work shown 

* 0.8 - answer incomplete 

* 0 - blank/unanswered 


# 15 

* $E(X) = 3(0.1) + 4(0.25) + 5(0.55) + 6(0.1) = 4.65$

* $Var(X) = (3-E(X))^2(0.1) + (4-E(X))^2(0.25) + (5-E(X))^2(0.55) + (6-E(X))^2(0.1) = 0.6284$

* question actually meant that the distribution is for 1 hour shifts and the question asks about 8hr days... so really need to compute $E(8X)$ and $Var(8X)$.... but not grading this way b/c I asked specifically for $E(X)$ and $Var(X)$ 


## Rubric

* 0.1 - found $E(8X)$ and $Var(8X)$  (not necessary but EC perhaps?) 

* 0.5 - correct expectation 

* 0.5 - correct expectation but no work 

* 0.5 - correct variance 

* 0.5 - correct variance but no work 

* 0.4 - correct variance given incorrect expectation

* 0.4 - correct work for variance but incorrect answer

* 0.4 - answer attempted but incorrect

* 0 - blank/unanswered 


# 16 

$X \sim N(5, 2^2)$ so $Pr(X \leq 3.5) = Pr\left(Z \leq \frac{3.5-5}{2} \right) = Pr(Z \leq -0.75) = 0.227$

(give most credit for work, little credit for correct reading of the Z table (since this involves some calculation work))

## Rubric

* 1 - correct 

* 0.9 - correct z-score

* 0.8 - correct z-score magnitude 

* 0.7 - correct picture

* 0.3 - credit for partial attempt 

* 0 - blank/unanswered 


# 17 

* in words, explain what follows a $Bin(n, p)$ distribution 

* define $n=50$ 

* define, in words, $p$ 

## Rubric

* 0.5 - defined a valid probability of success for p  

* 0.3 - defined what follows the binomial distribution

* ? - incomplete definition of the variable that follows the binomial distribution

* 0.2 - partial attempt 

* 0.2 - defined number of trials/sample size

* 0 - blank/unanswered 


# 18 

$X \sim Binom(5, 0.65)$ and we want to find $Pr(X \leq 2) = Pr(X=0) + Pr(X=1) + Pr(X=2) =0.235$

must display correct usage of binomial table 

(Note: $Pr(X = 2) = 0.811$.)

## Rubric

* 1 - correct 

* 0.8 - correct work, incorrect answer 

* 0.7 - incomplete answer (if they found at least $Pr(X=2)$ and $Pr(X=1)$)

* 0.5 - correct answer, incorrect work

* 0.5 - credit for attempt (if they just found $Pr(X=2)$)

* 0.3 - credit for partial attempt 

* 0.1 - incorrect answer no work 

* 0 - blank/unanswered 
