---
title: "Stat 11 Quiz 1"
date: "Month DAY, 2023"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
geometry: margin=1in
---

```{r setup, include=FALSE}
library(accessrmd)

knitr::opts_chunk$set(echo = F, message=F, warning=F)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(kableExtra)
library(knitr)
library(tidyverse)
library(png)
options(knitr.kable.NA = '')

theme_set(theme_bw())
```

**Academic Integrity** 

You are not allowed to receive or share any information during the quiz. To ensure compliance with the academic integrity policy outlined in the syllabus, I am asking you to read the following statement carefully before beginning this exam.

``I certify that all work is my own and that I will not discuss the content of this exam with anyone in or outside of class. I have not received any hints about the content or the question format of this exam. I understand that if I do have prior knowledge of what to expect on
this exam, I will not continue with the exam and may ask to be given the opportunity to make up these points elsewhere. I understand that either giving or receiving help on this exam constitutes serious academic misconduct and may be reported to the College Judiciary Committee, and will result in a full letter grade reduction from my final grade in the course.``

To certify that you have read and agree to the policy, please sign your name below.

\vspace*{1cm}

**Signature:** _____________________________ 

\vspace*{1cm}
**Instructions**

**Do not flip this page until instructed to do so.** The purpose of this quiz is to assess your understanding of the material we have covered thus far. This is not a perfect measure of your knowledge and does not predict your future statistical success. 

In general, you must show all work and/or explain your reasoning in order to get full credit or partial credit. You do not need to write in complete sentences for any of these questions but make sure that your handwriting is legible and your work is clearly labeled with your final answer clearly marked. You do not need a calculator but you may use one if you'd like. For any calculation problems, simply writing out the formula to find the answer will suffice.   

\vspace{1cm}
**First and Last Name:** _____________________________
\pagebreak


For Questions 1-5 suppose you are working with a team of scientists who want to study XX to determine XX. 


# Q1) 
Identify variable names and types and observational units 



# Q2)
Give a rough estimate of the sample correlation for the data in each of the scatterplots below.

OR 

At the beginning of the semester, we measured the width of a page in our statistics book two
times. Below is the scatterplot of the first measurement vs. the second measurement. 
1. Describe the relationship between the variables.
2. What effect does the starred point have on the correlation coefficient? That is, if the starred
point were removed, how would the correlation coefficient change, if at all?


# Q3) 
Identify whether a [scatterplot/boxplot] would or would not be an appropriate visual summary of the
relationship between the variables. In each case, explain your reasoning.

a. Age and height 
b. Location of birth and opinion about the right to free speech 
c. High school GPA and college GPA 
d. Dominant hand (left, right, or ambidextrous) and handwriting speed  


# Q4) 
Histogram and/or trend line to visualize which variables 



# Q5) 
Info from a mathematical summary statistic that isn't found in visual displays above. 



# Q6) 
Researchers wanted to compare two drugs, formoterol and salbutamol, in aerosol solution to a
placebo for the treatment of patients who suffer from exercise-induced asthma. Patients were to
take a drug or the placebo, do some exercise, and then have their “forced expiratory volume”
measured. There were 30 subjects available.
1. Should this be an experiment or an observational study? Why?
2. Within the context of this setting, what is the placebo effect?
3. Briefly explain how to set up a randomized blocks design (RBD) here.
4. How would an RBD be helpful? That is, what is the main advantage of using an RBD in a
setting like this? 

OR 

A gardener wishes to compare the yields of three types of pea seeds---type A, type B, and type
C. She randomly divides the type A seeds into three groups and plants some in the east part of
her garden, some in the central part of the garden, and some in the west part of the garden. Then,
she does the same with the type B seeds and type C seeds.
1. What kind of experimental design is the gardener using?
2. Why is this kind of design used in this situation? (Explain in the context of the situation.) 




# Q7) 
Distinguish random from arbitrary with justification
 

# Q8) 
Identify (or create) sample statistics and population parameters and RV for certain setting


# Q9)
Something about LLN 



# Q10)
Something about Gambler's fallacy 



# Sources 

$[1]$  

$[2]$  

$[3]$  

$[4]$  

$[5]$  