---
title: "Stat 11 Assessment Plans"
output: html_notebook
---


# Quiz 1 


## Collect/Gather Data
- consider confounding variables 
- ethical issues for experimental design 
- basics of experimental design (random sampling vs random assignment, blocking, control)


## Describe Data 
- describe distributions in terms of variability and location 
- interpret plots like density curves or histograms, bar charts, boxplots 
- switch perspectives from trend lines to histograms 
- use correlation to describe trends 
- summary stats including means and sample proportions



## Intro to RVs 
- normal distribution and binomial distribution 
- identify population, parameters
- able to distinguish randomness vs arbitrariness 
- fundamentals of random variables and sample spaces 
- expected value and variance of a random variable 
- LLN 
- Gambler's fallacy 



# Quiz 2 

## Connecting RVs to data 
- probability (and conditional probability) calculations based on contingency tables 
- independence based on contingency tables 
- sampling distributions compared to distributions of population RVs 
- visualize sampling distribution of sample proportion 
- CLT 
- standard deviation vs standard error 


## Inference for a single proportion
- how to generate valid CI for proportion 
- identify test statistic and p-value for single population proportion 
- define hypothesis for single proportion 

## Principles of inference more generally 
- different info in tests vs CIs 
- valid vs invalid interpretation of CIs 
- understand type I error rate 
- idea of sampling distribution revisited 


# Quiz 3 

## More methods 
- inference for single mean (especially sampling distribution)
- inference for difference in proportions 
- inference for difference in means 
- chi square procedures 

## Metacognitive 
- comparing one sided tests to two-sided tests 
- interpret test statistics relative to sd of sampling distribution 
- when to use different procedures 
- how to assess reliability of study conclusions 



# Final exam 


# GAISE Assessment Items for Q1 

Suppose that 20% of undergraduate students at a university own an iPad and 60% of graduate
students at the university own an iPad. Is it reasonable to conclude that 40% (the average of 20%
and 60%) of all students at the university (undergraduate and graduate students combined) own
an iPad? Explain why or why not, as if to a college student who has not taken a statistics class. 


Describe a situation where a third variable could be masking the relationship between two
variables.

Does everyone who scores below the median on this exam necessarily have a negative z-score
for this exam? Explain


Does the size of the standard deviation of a data set depend on the center of the distribution?
A. Yes, the higher the mean, the higher the standard deviation.
B. Yes, because you have to know the mean to calculate the standard deviation.
C. No, the size of the standard deviation is not affected by the location of the distribution.
D. No, because the standard deviation only measures how the values differ from each other, not
how they differ from the mean. 


A recent article in an educational research journal reports a correlation of +0.8 between math
achievement and overall math aptitude. It also reports a correlation of -0.8 between math
achievement and a math anxiety test. Which of the following interpretations is the most correct?
A. The correlation of +0.8 indicates a stronger relationship than the correlation of -0.8.
B. The correlation of +0.8 is just as strong as the correlation of -0.8.
C. It is impossible to tell which correlation is stronger. 



A researcher is studying the relationship between an experimental medicine and T4 lymphocyte
cell levels in HIV/AIDS patients. The T4 lymphocytes, a part of the immune system, are found at
reduced levels in patients with the HIV infection. Once it is established that the two variables –
dosage of medicine, and T4 cell levels – are highly correlated, what type of study needs to be
done to establish that a change in dosage causes a change in T4 cell levels?
A. correlational study
B. controlled experiment
C. prediction study
D. survey 



A study found that individuals who lived in houses with more than two bathrooms tended to have
higher blood pressure than individuals who lived in houses with two or fewer bathrooms. Can a
cause-and-effect conclusion be drawn from this? Why or why not? 



An article on the CNN web page begins with the sentence, “Family doctors overwhelmingly
believe that religious faith can help patients heal, according to a survey released Monday.”
Later, the article states, “Medical researchers say the benefits of religion may be as simple as
helping the immune system by reducing stress,” and Dr. Harold Koenig is reported to say that
“people who regularly attend church have half the rate of depression of infrequent churchgoers.”

Use the language of statistics to critique the statement by Dr. Koenig and the claim, suggested by
the article, that religious faith and practice help people fight depression. You will want to select
some of the following words in your critique: observational study, experiment, blind, doubleblind, precision, bias, sample, spurious, confounding, causation, association, random, valid, and
reliable. 



The scatterplot shows how divorce rate and marriage rate (both as number per year per 1000
adults) are related for a collection of 10 countries. The regression line has been added to the
plot. 

1. The U.S. is not one of the 10 points in the original collection of countries. It happens that the
U.S. has a higher marriage rate than any of the 10 countries. Moreover, the divorce rate for the
U.S. is higher than one would expect, given the pattern of the other countries. How would
adding the U.S. to the data set affect the regression line? Why?

2. Think about the scatterplot and regression line after the U.S. has been added to the data set.
Provide a sketch of the residual plot. Label the axes and identify the U.S. on your plot with a
triangle. 





Students collected data on a random sample of 12 breakfast cereals. They recorded x = fiber (in
grams/ounce) and y = price (in cents/ounce). A scatterplot of the data shows a linear relationship.
The fitted regression model is
yˆ = 17.42 + 0.62x
The sample correlation coefficient (r) is 0.23. The standard error of the sample slope is 0.81.
Also, sy|x = 3.1.
1. Find r2 and interpret r2
 in the context of this problem.
2. Suppose a cereal has 2.63 grams of fiber/ounce and costs 17.3 cents/ounce. What is the
residual for this cereal?
3. Interpret the value of sy|x in the context of this problem. That is, what does it mean to say that
sy|x = 3.1?
4. In the context of this problem, explain what is meant by “the regression effect.” 





An internet company is planning to test which of two online ad campaigns is more effective in
generating clicks on their site. Outline the design of an experiment you would use to achieve this
goal. Assume you have money to place 500 ads for each of the two possible campaigns. 




ITEM 38
A study in the Journal of Leisure Research investigated the relationship between academic
performance and leisure activities. Each in a sample of 159 high-school students was asked to
state how many leisure activities they participated in weekly. From the list, activities that
involved reading, writing, or arithmetic were labeled “academic leisure activities.” Some of the
results are in the table below: 

Based on these numbers (and knowing that the GPA is a value between 0 and 4 and the number
of activities cannot be negative), discuss the potential skewness of each of the above variables. 


ITEM 39
A random sample of 200 mothers and a separate random sample of 200 fathers were taken. The
age of the mother when she had her first child and the age of the father when he had his first
child were recorded.
1. Describe the data for the mothers' age.
2. Describe the data for the fathers' age.
3. Compare the distributions.
4. A suggestion is made to check the correlation between the ages if we wish to compare the two
populations. Is this a good suggestion? Why or why not?

ITEM 40
When conducting a randomized experiment, the original randomization of units to treatment
groups breaks the association between
1. the explanatory variable and the response variable.
2. the explanatory variable and confounding variables.
3. the response variable and confounding variables.

ITEM 41
When conducting a randomization test, the simulated re-randomization of units to treatment
groups breaks the association between
1. the explanatory variable and the response variable.
2. the explanatory variable and confounding variables.
3. the response variable and confounding variables.


*** 



You are a busy tourist and have only 10 minutes to sit around and watch the geyser. But you can
choose when to arrive. If the last eruption occurred at noon, what time should you arrive at the
geyser to maximize your chances of seeing an eruption?
1. 12:50pm
2. 1:00pm
3. 1:05pm
4. 1:15pm
5. 1:25pm

Roughly, what is the probability that in the best 10-minute interval, you will actually see the
eruption?
1. 5%
2. 10%
3. 20%
4. 30%
5. 50%
6. 75%

A simple measure of how faithful is Old Faithful is the interquartile range. What is the
interquartile range, according to the boxplot above?
1. 10 minutes
2. 15 minutes
3. 25 minutes
4. 35 minutes
5. 50 minutes
6. 75 minutes

Not only are you a busy tourist, you are a smart tourist. Having read about Old Faithful, you
understand that the time between eruptions depends on how long the previous eruption lasted.
Here's a box plot indicating the distribution of inter-eruption times when the previous eruption
duration was less than three minutes. 

You can easily ask the ranger what was the duration of the previous eruption. What is the best
10-minute interval to return (after a noon eruption) so that you will be most likely to see the next
eruption, given that the previous eruption was less than three minutes in duration?
1. 12:30 to 12:40
2. 12:40 to 12:50
3. 12:50 to 1:00 
4. 1:15 to 1:25
5. 1:25 to 1:35

How likely are you to see an eruption if you return for the most likely 10-minute interval?
1. 5%
2. 10%
3. 20%
4. 30%
5. 50%
6. 75% 