---
title: "Stat 11 Proposed Calendar"
author: "Prof. Suzy Thornton"
date: "Spring 2023"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

```{r include=FALSE}
library("accessrmd")

colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}

```



We will cover three different, but related, units in this one-semester course. These units roughly correspond to the first six parts of your textbook. The units are broken into the following subject areas:


**Unit 1**

- Exploring and understanding data 
- Exploring and understanding relationships between variables 
- Collecting data 


**Unit 2**

- Randomness and probability


**Unit 3**

- Statistical inference from a single sample of data 
- Statistical inference from multiple samples of data 
- Statistical inference for related variables 

<br><br>

In the calendar below **IHW** corresponds to an individual homework assignment and **GHW** corresponds to group homework assignments.

|Week |Date |Unit |Topics |Reading and homework assignments and assessment items |
|:--- |:--- |:--- |:--- |:--- |
| 1 | Jan 17 | 1 | Visualizing and summarizing numeric data | Part 1: Ch 1-3 <br> IHW 1+2 |
| 2 | Jan 23 | 1 |  Describing distributions with variability  | Part 1: Ch 4-5 <br> GHW 1  |
| 3 | Jan 30 | 1 |  Describing relationships between two numeric variables | Part 2: Ch 6-8 <br> IHW 3+4 |
| 4 | Feb 6 | 1   | Collecting data from experiments and observational studies | Part 3: Ch 10-11 <br> GHW 2 |
| 5 | Feb 13 | 1  | All previous topics | IHW 5 <br> **Quiz 1** |
| 6 | Feb 20 | 2 |  From randomness to probability and the laws of probability | Part 4: Ch 12-13 <br> IHW 6+7 |
| 7 | Feb 27 | 2 |  Random variables and probability models | Part 4: Ch 14-15 <br> GHW 3 <br> IHW 8 |
| 8 | Mar 6 |   | Spring Break |   | 
| 9 | Mar 13 | 2 |  All previous topics | IHW 9+10 <br> **Quiz 2** |
| 10 | Mar 20 | 3 | Sampling distributions and confidence intervals for a proportion and for a mean | Part 5: Ch 16-17 <br> IHW 11+12 |
| 11 | Mar 27 | 3 | Hypothesis tests about a proportion or a mean | Part 5: Ch 18-19  <br> GHW 4 |
| 12 | Apr 3 | 3 | Comparing grouped numeric data | Part 6: Ch 20-21 <br> IHW 13+14 |
| 13 | Apr 10 | 3 | All previous topics | IHW 15 <br> **Quiz 3** |
| 14 | Apr 17 | 3 | Comparing grouped categorical data | Part 6: Ch 22 <br> GHW 5 |
| 15 | Apr 24 | 3 | Inference for linear relationships | Part 2: Ch 9 and Part 7: Ch 23-24 <br> IHW 16 <br> **Final Project Presentations** |
| 16 |  May 4-11  |  |  **Final Exam** |  |


<br><br>

`r colorize("Please understand that this calendar is subject to change depending on the discression of your professor. Check back regularly for updates.", "red")`



