---
title: "Stat 11 Week 1"
subtitle: "Data and Statistics" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---




# 1. What is data? 

## Structure of data 

Variables - something that varies 

Observational units 

```{r echo=FALSE}
rows = NULL
for(i in 1:10){
rows = c(rows,paste0("observational unit ", i))
}
set.seed(101)
sample_data <- data.frame(ID = rows,
            Variable1 = rnorm(10, 10, 2),
            Variable2 = rpois(10, 2),
            Variable3 = sample(c("Red", "Green"), size=10, replace=TRUE))

sample_data
```

## Measurability or countability 

   - numeric or quantitative 
   - categorical or qualitative 
   - context matters 


# 2. What is statistics? 

Machine learning, computer science, data science, demography, modeling, mathematics, natural science, liberal art? 

<span style="color:blue">What is your relationship to statistics?</span>


## Exploring vs confirming 

<span style="color:blue">What is a question you would like to answer with statistics?</span>

Is it exploratory or confirmatory? 



# 3. About this class 

The Textbook and Pearson MyLab are required. Attendance is required. 

Everything you need for this class can be found on Moodle! 

## Analyzing data 

You will be using software (either Excel or RStudio) to analyze data. There is an Intro to R (and RStudio) two-part workshop being held by the Stat Clinicians. Bring your own laptop! (Let me know if you need to borrow one from the department.)

* Part 1 in SC 104 - Either Jan 18 (W) or Jan 19 (Th) from 8-10pm. 

* Part 2 in SC 105 - Either Jan 22 (Su) or Jan 24 (Tu) from 8-10pm. 


## Syllabus 

<span style="color:purple">By yourself:</span>
Take a few minutes to read over the syllabus. 

- What stands out to you? 

- What do you think is going to be the most important thing you can do to succeed in this class? 

- What do you think will be your biggest obstacle? 

<span style="color:purple">With someone else:</span>

Share your answers with a neighbor. Strategize how to handle what you each expect will be your biggest obstacles. 


**Prof Suzy's Recommendations** 

- *Read* your textbook!

- *Practice* asking and answering questions in class and while you read your textbook or do your homework.

- Attend *Office Hours* as often as possible, this time is for you so use it!

- *Communicate* with your professor. Keep me in the loop! 

- Allow yourself *room to grow*. We learn and live at our own paces. You're not perfect and you don't have to be.


