---
title: "Stat 11 Week 2"
subtitle: "Comparing Entire Distributions" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

<span style="color:purple">example text</span>


Math world (RV as a model) vs real world (observable sample data)

# What is a distribution? 

Possibilities and Probabilities 

## Recap: Normal/Gaussian Distribution 

## Examples 

Uniform

Chi-square 


For now, going to focus on numeric variables. 



# Comparing Distributions of Numeric Variables 

Five number summary 

Q: what can you tell from a histogram that you can't tell from a 5 numb summary? 

Recall: When to use the mean vs the median? When to use standard deviation vs IQR? 


Grouped data displays 

Histograms [find example of grouped histograms]

[boxplots image from last class slides] 

## Quantiles and percentiles  

compare/contrast for std normal model, non-std normal, and another continuous model 

[draw pic highlight values for quantiles changed, 68/95/99.7]

Normal probability plots - plot each data point against it's z-score. Straight line means these values match up well and a Normal/Gaussian model is likely reasonable. 

### Quantiles and percentiles of a standard Normal distribution

Example question: 

[draw pic]


## Re-expressing (transforming) data 

Recall Week 1 notes on standardization 

shifts and scales 
