---
title: "Stat 11 Week 5"
subtitle: "Review of Unit 1" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

# Unit 1 topics 

* Exploring and understanding data

* Exploring and understanding relationships between variables


# Week 1 - Visualizing and summarizing data 


* Data 

  * Observational units 

  * Variables - categorical or numeric - and their distributions 

* Analysis 

  * Confirmatory or exploratory 

  * Sample statistics 
  
## For categorical variables 

* Contingency tables and independence 

* <span style="color:green">Simpson's Paradox and lurking variables</span> 

# Week 2 - Describing distributions of numeric variables with variance 


* Shape and measures of center and spread 

  * Mean vs median 
  
  * Variance vs IQR 

* Normal model and the 68/95/99.7% rule 

* Transforming variables 

  * Shifts and scales 
  
  * Standardization 

* Quantiles and quartiles  

  * Normal QQ Plots 


# Week 3 - Describing relationships between two numeric variables 

* Simple linear regression model 

  * Predicted/fitted values and residuals 

  * Standard error of the residuals 

* Correlation and the coefficient of determination 

* Variable roles 

* Variable transformations

* <span style="color:green">Regression to the mean</span> 



## Watch out for 

* <span style="color:green"><span style="color:green">Extrapolation</span> 

* Outliers, <span style="color:green">leverage</span>, and <span style="color:green">influence</span> 

* Model assumptions met  



