---
title: "Introduction"
author: "STAT 011 with Prof Suzy"
institute: "Swarthmore College"
output:
  xaringan::moon_reader:
 #   css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
    self_contained: false # if true, fonts will be stored locally
#    includes:
 #     in_header: "assets/mathjax-equation-numbers.html"
    nature:
#      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
      navigation:
        scroll: false # disable slide transitions by scrolling
includes:
  in_header: mystyles.sty
---

```{r setup_pres, include=FALSE, echo=FALSE}
#devtools::install_github("ropenscilabs/icon")
#devtools::session_info('rmarkdown')

knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings

rm(list=ls())
library('tidyverse')
library('gridExtra')
library('broom')
library('cowplot')
library("RefManageR")
library("DT")

```

```{css, echo=FALSE}
pre {
  background: #FFBB33;
  max-width: 100%;
  overflow-x: scroll;
}

.scroll-output {
  height: 70%;
  overflow-y: scroll;
}

.scroll-small {
  height: 50%;
  overflow-y: scroll;
}
   
.red{color: #ce151e;}
.green{color: #26b421;}
.blue{color: #426EF0;}
```

## Today 

1. My Stats Journey 

2. About This Class  

3. Meet Your Group 

4. Reflection Prompt

5. Preparing for Thursday's class

---
# My Stats Journey 

(5 mins)

---
# About This Class 
## What can we do with data & statistics? 

Example stats about covid from Amanda's slides  (go over a really abbreviated version)

(10 mins) 

---
# About This Class 
## General flow of the course 

instructions on how classes will go 

(5 mins)

---
# About This Class 
## Syllabus highlights 


Homework due dates and frequency 

Midterm dates, in-class 

Final Project 

Getting stats help


(10 mins)

---
# About This Class 
## Tools for this course 

Moodle (course calendar)

Gradescope 

RStudio server 

(10 mins)

---
# Questions so far? 
## 5 mins

---
# Meet Your Group
## 20 mins 


 choose group, icebreaker, group expectations (including masks); hand in signed expectations

Non-negotiable guidelines (see syllabus)


---
# Questions so far? 
## 5 mins

---
# Reflection Prompt 
## 10 mins 

what is your relationship to data or statistics? 

And what is a question you would like to answer with statistics? 


---

## Prepare for Thursday's class 

- Access Moodle
- Read Ch 1 and 2 of your textbook 
- Follow the RStudio Instructions for HW 1 
- HW 1 Problem 5 

Exploratory data analysis with some data on global wealth and health 
