---
title: "Exploring data"
author: "STAT 011 with Prof Suzy"
institute: "Swarthmore College"
output:
  xaringan::moon_reader:
  #   css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
  self_contained: false # if true, fonts will be stored locally
#    includes:
#     in_header: "assets/mathjax-equation-numbers.html"
nature:
  #      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
  highlightStyle: github
highlightLines: true
countIncrementalSlides: false
ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
navigation:
  scroll: false # disable slide transitions by scrolling
includes:
  in_header: mystyles.sty
---
  

```{r setup_pres, include=FALSE, echo=FALSE}
#devtools::install_github("ropenscilabs/icon")
#devtools::session_info('rmarkdown')


# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy = FALSE, # display code as typed
  size = "small" # slightly smaller font for code
)

knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings

rm(list=ls())
library(tidyverse)
#library('gridExtra')
#library(broom)
data <- read_csv("Data/global_wealth_and_health.csv")
data2 <- data  %>% filter(!is.na(Value)) %>% 
               filter(Time=="2018") %>% 
               select(-c('Flag Codes', Flags, LOCATION, TIME, Time, DEMO_IND)) 
data3 <- pivot_wider(data2, id_cols=Country, names_from = Indicator, values_from = Value)
global_wealth_and_health <- data3[,-c(4,9,13)]
colnames(global_wealth_and_health) = c("Country", "FertRate", "LifeExpect", "MortRate", 
      "HIVPrev", "RuralPop", "GDP", "TotalExpenditure", "TotalPop", "SrPop", "YoungPop", "PovertyCount")
```

```{css, echo=FALSE}
pre {
  background: #FFBB33;
  max-width: 100%;
  overflow-x: scroll;
}

.scroll-output {
  height: 70%;
  overflow-y: scroll;
}

.scroll-small {
  height: 50%;
  overflow-y: scroll;
}
   
.red{color: #ce151e;}
.green{color: #26b421;}
.blue{color: #426EF0;}
```
     
## Today 

1.  Final group round-up and meet and greet 

2.  Quick summary of describing and exploring data 

3.  Continue with class 4's worksheet 

4.  Reflection prompt 

5.  Prep for next class 


---
## Final group round-up (10 mins)

Now that drop-add has ended we have $39$ students enrolled in this class. Please separate yourselves into $7$ groups of five and $1$ group of four. 

Raise your hand if you do not have a group **or** are in a group of size $3$.  

If there's any one new in your group, take a minute to introduce everyone. Then, go over your group contracts once more and finalize your group name. 

**Note about seating arrangements:** 

Try to sit near your group mates for the rest of the semester. There should be exactly four groups situated on each side of the class room. Please leave the aisles open for me to walk around and answer questions. 

The best arrangement for group communication seems to be three people at one desk and two people at another desk in front of the others. This way, only two people have to turn around for the group work and discussions and everyone is facing one another in a circle-ish arrangement. 


*If you have any concerns about your group or this seating arrangement, please send me an email so I can take your comments into consideration.*


---
## Describing and Exploring Data 


What is an *observational unit*? How does this compare to *units of measurement*? 


--
What is a *variable*? 


--
Relationships between variables 

   * two quantitative 
   
   * one quantitative, one categorical 
   
   * two categorical 
   
Determining if a quantitative variable seems to follow a Normal distribution 

  * Look for symmetry and unimodality 
  
  * Determine if the 68, 95, 99.7 percent rule applies 
  
  * Create a Normal Probability Plot and compare deviations from the diagonal line 




---
## Group work
### 20 mins 

* Download or open the Class 4 R Markdown worksheet in RStudio. Make sure you can knit the template first! 

* Then work with your group members to answer the $7$ questions. 

* The group reporter will submit your completed R Markdown document via Moodle for participation credit before the end of class. 

* Raise your hand if your group has a question! 


**Note:** If your group finishes early, use this time to either review HW 2 together or get started on today's reflection prompt. 


---
## Class discussion follow-up

* Normally distributed data (AKA Gaussian data) 

* Histograms and density curves 

* Normal probability plots and quantiles 

* 68/95/99.7 rule 


---
## Reflection prompt 
### Spurious Correlations

* Complete the reflection prompt under the Week 3 section of our Moodle page for a participation point. 


* We will stop at 11:05 to discuss preparing for our next class. 


**Note:** This prompt is only open for edits until noon today so do your best to finish it in class! 


---
## Prepare for Thursday's class 

* Read chapter 10 in your textbook. (And catch up on any reading for chapters 1-6 if needed!)

* Submit your HW 2 solutions by noon tomorrow. Solutions to HW 1 will be posted tonight. Solutions to HW 2 will be posted tomorrow afternoon. 

* Read and knit the HW 3 template. Note that you first need to download the `class_survey.csv` file to the same location as your HW 3 R Markdown document for this template to knit! 
  
* If you have a planned absence from class **during an exam day**, you must notify me by the end of September. In general, no other late exam arrangements will be permitted.

Next class, we will dig deeper into the concepts of randomness and variability and consider the pros and cons of different sampling strategies. 

**BTW:** The new Mu-se schedule has been posted on our calendar and on the Math/Stat department's website. 



