---
title: "Pausing to Reflect and Ethical Considerations"
author: "STAT 011 with Prof Suzy"
institute: "Swarthmore College"
output:
  xaringan::moon_reader:
  #   css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
  self_contained: false # if true, fonts will be stored locally
#    includes:
#     in_header: "assets/mathjax-equation-numbers.html"
nature:
  #      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
  highlightStyle: github
highlightLines: true
countIncrementalSlides: false
ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
navigation:
  scroll: false # disable slide transitions by scrolling
includes:
  in_header: mystyles.sty
---
  

```{r setup_pres, include=FALSE, echo=FALSE}
#devtools::install_github("ropenscilabs/icon")
#devtools::session_info('rmarkdown')


# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy = FALSE, # display code as typed
  size = "small" # slightly smaller font for code
)

knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings

rm(list=ls())
library(tidyverse)
#library('gridExtra')
#library(broom)
data <- read_csv("Data/global_wealth_and_health.csv")
data2 <- data  %>% filter(!is.na(Value)) %>% 
               filter(Time=="2018") %>% 
               select(-c('Flag Codes', Flags, LOCATION, TIME, Time, DEMO_IND)) 
data3 <- pivot_wider(data2, id_cols=Country, names_from = Indicator, values_from = Value)
global_wealth_and_health <- data3[,-c(4,9,13)]
colnames(global_wealth_and_health) = c("Country", "FertRate", "LifeExpect", "MortRate", 
      "HIVPrev", "RuralPop", "GDP", "TotalExpenditure", "TotalPop", "SrPop", "YoungPop", "PovertyCount")
```

```{css, echo=FALSE}
pre {
  background: #FFBB33;
  max-width: 100%;
  overflow-x: scroll;
}

.scroll-output {
  height: 70%;
  overflow-y: scroll;
}

.scroll-small {
  height: 50%;
  overflow-y: scroll;
}
   
.red{color: #ce151e;}
.green{color: #26b421;}
.blue{color: #426EF0;}
```
     
## Today 

1.  Easy (finger's crossed!) R practice 

2.  Reflection with your new/final (finger's crossed!) group mates 

3. The ASA's Ethical Guidelines for Statistical Practice

4.  Preparing for next week and your first in-class test (don't panic!)


---
## Easy R Practice 
### (If I didn't jinx it!)


1. Log in to RStudio on the cloud.

2. Try to knit the HW 3 template.  

3. If you are successful, stand up and stretch for a minute. 


<br>

<br>

--
Now, we are going to revisit the Class 4 worksheet once again. Open (or download from Moodle) the "solved" version of the Class 4 worksheet and follow along with me as we worth through this together. 


---
## Reflecting with your group


First, let's arrange ourselves for a harmonious group work setting. Please sit near your new group mates for the rest of the semester. There should be exactly four groups on each half of the classroom. 

Here's a diagram of how this will work: 


<br>

<br>


<br>

<br>


<br>

<br>


*If you have any concerns about your new group or this seating arrangement, please send me an email so I can take your comments into consideration.*


---
## Reflecting with your group

Spend the next 7 minutes working with your group mates to come up with three main points you have learned about statistics thus far. (No more than one of these main points should be about R or programming!) 

Your group reporter should take notes on what your final three main points are and be prepared to share them with the class. 

<br>

<br>

--
Now let's talk about these main points together! 



---
## ASA Guidelines for Statistical Practice 

Spend three minutes reading through the guidelines created by the American Statistical Association. 


Pay close attention to the guidelines for 

* Professional Integrity and Accountability 

* Integrity of data and methods 

* Responsibilities to Research Subjects 


<br>

<br>


--
Assign someone to be the group reporter and complete as much of the Class 6 worksheet as you can with your group mates. 

I will look over your responses to inform our discussions next week! 





