---
title: "Stat 11 Week 13"
subtitle: "Review of Unit 3" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


# Unit 3 topics (that we've covered thus far)

* 

Additional topic for final: 


## Effect size 

## Practical vs statistical significance 


## Types of conclusions 

The only way to reduce both types of error is to collect more evidence or, in statistical terms, to collect more data.

* $\alpha = Pr(\text{Type I error})$: If $H_0$ is true, this is the probability that we (incorrectly) reject it.

* $\beta = Pr(\text{Type II error})$: If $H_0$ is false, this is the probability that we (incorrectly) fail to reject it. 

* $1-\beta = Power$ If $H_0$ is false, this is the probability that we (correctly) reject it.  




# Week 4 - Collecting data from experiments and observational studies

*  


## Example 
 



# Week 6 - From randomness to probability and the laws of probability

*  


## Example 
 

# Week 7 - Random variables and probability models

*  


## Example - Week 7 In-class Worksheet 

***

# Study tips 

## Have you....

1. Read the relevant sections of Chapters 10 - 15? 

2. Completed IHW #5 - #10? 

3. Checked your answers to GHW #3 with the solution key? 

4. Taken notes on which topics or examples are most challenging to you? 

***
  
# Student Requested Examples 
  
## 

***

# Looking ahead 
 