---
title: "Stat 11 Week 7"
subtitle: "Random Variables" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Recall 

Random phenomena are often modeled as random variables. Random variables are mathematical objects (functions, actually) that have an associated probability distribution function. 

A probability distribution must always specify:

* possibilities (elements of the *sample space*) and 

* probabilities. 

  
# 1. Expected value 

When referring to measures of centrality for a theoretical random variable, we typically are interested in the mean. Since we are dealing with the mathematical object, we use a new terminology to indicate that this measure of centrality is a theoretical value. Instead of calling this the mean/average of the random variable, we call this value the <span style="color:green">expected value</span> of the random variable. 

The theoretical mean of a random variable $X$, AKA the expected value of $X$ is: 

*the sum of all possibilities times their corresponding probabilities*. 
  
$$E(X) = \sum_{x\in S} \left[ x \times Pr(x) \right]$$   
  
# 2. Variance and standard deviation  

There is no new terminology when referring to measures of spread for a theoretical random variable. We still use variance and standard deviation to refer to these measures. 

Similar to calculating the variance of a sample of data, the variance of a random variable is:

*the expected value of the (squared) distance from each possibility to the mean possibility (the expected value) times the corresponding probabilities*.

$$Var(X) = \sum_{x \in S} \left[(x-E(X))^2\times Pr(x)\right]$$ 

The standard deviation of a random variable $X$ is still just the square root of the variance: $st.dev(X) = \sqrt{Var(X)}$. 


## Week 6 In-Class Worksheet: Part 2 

**Instructions:** Let's plan a trip. Suppose $8$ of us are going to travel to attend one of two international statistics conferences. (The rest of us are attending non-statistical conferences, naturally.) We need to request funding so we can travel to and from our destinations. Suppose $3$ of us are flying to Toronto, Canada for the 2023 Joint Statistical Meeting and $5$ of us are flying to the International Chinese Statistical Association conference in Chengdu, China.  

Airline ticket prices vary from time to time, but for simplicity, let's assume we're going to purchase all tickets for the same destination at the same price. Suppose also that past experience has shown that tickets to Toronto have a mean price of $\$563$, with a standard deviation of $\$70$, while the mean airfare to Chengdu is $\$5400$, with a standard deviation of $\$750$.

<span style="color:purple">4. Define two random variables and use them to express the total amount of funding we will need to request to fly to both of these statistics conferences.</span>

<br>
<br>

One possible solution is to let $X$ represent the random cost of an airline ticket from PHL to Toronto, and let $Y$ represent the random cost of an airline ticket from PHL to Chengdu: 

$$X = \text{ cost of a flight from PHL to Toronto} \\ Y = \text{ cost of a flight from PHL to Chendu}$$

Then, according to the information above, we have that 

$$E(X) = 563, \quad Var(X) = 563^2 \\ E(Y) = 5400, \quad Var(Y) = 750^2.$$



# 3. Correlation and Covariance 

Correlation and <span style="color:green">covariance</span> measure the same thing: the strength of a linear trend between two random variables. The only difference between these two measurements is that correlation is easier to interpret because it is a standardized version of covariance, i.e. correlation is always between $-1$ and $1$. Covariance, on the other hand, could be any number from $-\infty$ to $+\infty$. Because of this, although we have practiced calculating the correlation for a sample of data with two numeric variables, we have not calculated the sample covariance, even though we technically could.  

Conversely, when discussing theoretical random variables, we tend to describe their covariance rather than their correlation. 

$$Cov(X,Y) = E\left[(X-E(X))\cdot(Y-E(Y)) \right] = \sum_{x \in S} \left[(x-E(X)(y-E(Y))\times Pr(x \text{ and }y)) \right]$$

## Example: Modeling ariline tickets 

<span style="color:purple">Q) How could we interpret the covariance between the price of a ticket from PHL to Toronto and the price of a ticket from PHL to Chengdu?</span> 


Note, the covariance between any random variable and itself is actually just another way of expressing the variance: $Cov(X,X) = Var(X)$. 


The relationship between correlation and covariance is this:

$$Cor(X,Y) = \frac{Cov(X,Y)}{\sqrt{Var(X)Var(Y)}}.$$


**Note:** In every formula given above, the terms involved can each be described as some functions of the *possibilities* and their corresponding *probabilities*. This is why we say that a probability distribution must specify only these two things: the possible values of the random variable and the probabilities associated with these possible values.  


***

There is a lot of new notation and vocabulary to become familiar with as we begin to understand how probability and random variables operate. I've created a [random variables and probability reference sheet](https://profsuzy.github.io/Stat11/Cheat-sheet-2.html) to help summaries some of these new concepts; however, I recommend that you create a reference sheet of your own to help you study the material for Quiz 2. 