---
title: "Stat 11 Week 14"
subtitle: "Practce with Comparing Counts and Ethical Stats" 
author: "Prof. Suzy Thornton"
date: "Spring 2023"
lang: "en-US"
output:
  html_document:
    df_print: paged
header-includes:
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{amsfonts}
- \usepackage{xcolor}
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


# 1. Data Introduction 

The [in-class worksheet for this week](https://profsuzy.github.io/Stat11/wk14-wksheet.html) is all about practicing statistical inference for categorical variables! 

Recall we have learned the following procedures: 

* Chi-square goodness of fit 

  * $H_0: p_{1} = p_{1,0}, p_{2} = p_{2,0}, p_{3} = p_{3,0}, \dots, p_{k} = p_{k,0}$

  * Example: Does the distribution of beak types for finches on the San Cristobal island match the distribution of beak types for finches on the Pinta island. On Pinta island $56\%$ of the finches have the first beak types, $30\%$ of the finches have the second beak types, $7\%$ have the third type, and $7\%$ have the fourth type.

* Chi-square test of homogeneity 

  * $H_0: p_{1} = p_{2} = p_{3} =  \cdots = p_{k}$

  * Example: Are all the flavors of jelly beans evenly distributed in the packages sold at a supermarket? 

* Chi-square test of independence 

  * $H_0:$ Categorical variable $X$ is independent of categorical variable $Y$. 

  * Example: Is whether or not a person aboard the Titanic survived independent of their class status? 

# 2. Analysis Goals  

* Recognize whether or not a statistical question involves count data. 

* Determine which chi-square procedure is appropriate for different inference questions about count data. 


# 3. Summary of Results  

* Just because some data can be presented in tabular format doesn't mean that it is count data! 

* Although the format of the null and alternative hypotheses are standard for each procedure, translating these statements about population parameters into a particular applied context takes careful thought. 

# Reflection 

Let's take a minute to review our previous in-class worksheets. 

## Unit 1 

  * [Visualizing Data](https://profsuzy.github.io/Stat11/wk2-wksheet.html) and [followup activity about misleading conclusions from statistical analyses](https://profsuzy.github.io/Stat11/wk2-wksheet-followup.html)

  * [Fitting a Linear Regression Model](https://profsuzy.github.io/Stat11/wk3-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week3-3-S23.html)
  

## Unit 2 

  * [Designing a Statistical Study](https://profsuzy.github.io/Stat11/wk4-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week4-3-S23.html)
  
  * [Experimenting with Probability](https://profsuzy.github.io/Stat11/wk6-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/wee6-3-S23.html)
  
  * [More Experiments with Probability](https://profsuzy.github.io/Stat11/wk7-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week7-3-S23.html)
    

## Unit 3 

 * [Experiments with Confidence Intervals](https://profsuzy.github.io/Stat11/wk10-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week10-3-S23.html)
      
 * [Practicing with Hypothesis Tests](https://profsuzy.github.io/Stat11/wk11-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week11-3-S23.html) and [solutions](https://profsuzy.github.io/Stat11/wk11-wksheet-solns.html)
        
 * [Reviewing Methods of Unit 3](https://profsuzy.github.io/Stat11/wk13-wksheet.html) - [summary of results](https://profsuzy.github.io/Stat11/week13-3-S23.html) and [solutions](https://profsuzy.github.io/Stat11/wk13-wksheet-solns.html)
 
 * [Solutions for Practice with Chi-square Procedures](https://profsuzy.github.io/Stat11/wk14-wksheet-solns.html)
          
