---
title: "In-Class Worksheet"
author: "STAT011 with Prof Suzy"
date: 'Week 13: Reviewing Methods of Unit 3'
output:
  html_document: default
  pdf_document: default
---
<br>
**Name:** _____________________________________

<br>
**Instructions:** There are 5 questions in this worksheet. You will work with your group members to answer each question. Before getting started, take a moment and reflect on ways in which you can show your assigned group members respect. You may also view this initial [list of examples](https://docs.google.com/document/d/1emP8SiS2IO-_blKdVmVp-CJTr0NLlKG4vzMnphH-P7E/edit?usp=sharing) that we will add to over the semester.

**Briefly,** in the space below, specify one way in which you will work to show your group members respect during today's lesson:

<br>
<br>
<br>

```{r setup, echo=FALSE, include=FALSE}
require(knitr)
library(tidyverse)
knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings
```


## 1.  By yourself, read each problem setting and determine if the problem is about proportions or means. 

\vspace{1cm}

## 2.  On your own, guess which of the following statistical inference techniques is most relevant for each problem. 

**Statistical inference techniques** 

A. One-sample t-procedures for a mean.

B. Two-sample t-procedures for comparing means.

C. Paired-sample t-procedures.

D. One-sample z-procedures for a proportion.

E. Two-sample z-procedures for comparing proportions.


## 3.  With your group, go over your answers from Problem 2. Once you all agree on which inference technique to use, determine whether a confidence interval or a hypothesis test is most appropriate for each problem. 


* Confidence interval: useful when we are interested in estimating an actual effect size.

* Hypothesis test: useful when we primarily need to make a decision. 


## 4.  With your group, go over the research questions that you would answer with a hypothesis test and specify the null and alternative. 

\vspace{1cm}

## 5. Analyze each research question and determine if the data was collected through an observational study or an experiment. Determine how this information would impact the scope of your conclusions in each problem. 

\pagebreak 

# Research questions 

1. One hundred insomnia patients are randomly selected for a clinical trial. Fifty are randomly assigned to a placebo and the other $50$ are given a mild sedative. Which subjects sleep more hours and how many more hours do they tend to sleep? 

\vspace{1cm}

2. Health recommendations suggest walking $10,000$ steps per day. Suppose that you collect data from a sample of Fitbit users and you want to determine if they average more than $10,000$ steps per day. 

\vspace{1cm}

3. Are people who smoke tobacco cigarettes more likely to suffer from lung cancer than people who smoke marijuana cigarettes? 

\vspace{1cm}

4. The manager of a company’s human resource department examines employee attendance records to investigate whether more than $20\%$ of employee sick days are taken on Fridays.

\vspace{1cm}

5.  An advocacy organization surveys $960$ Canadians to see how many report being born in another country. Similarly, $1250$ U.S. citizens are asked whether or not they were born in a foreign country. The researchers want to determine if the proportion of foreign born people is the same in the United States as in Canada. 

\vspace{1cm}

6.  A group of college freshmen are asked about the quality of the university cafeteria. A year later, the same students are asked about the cafeteria quality again. Do student's opinions change during their time at school? 

\vspace{1cm}

7. Do cows tend to produce more milk if their handler speaks to them by name every day than if the handler does not speak to them by name? A farmer randomly assigned half of her cows to each group and then compared how much milk they produced after one month. 

\vspace{1cm}

8. A recent survey investigated how much more likely American parents are to playing video games in their down-time compared to American adults who do not have children. 

\vspace{1cm}

9. A researcher is interested in studying whether Americans gained weight, on average, while in quarantine by virtue of the COVID-19 pandemic. She took a random sample of Americans and asked their weight before the pandemic and their weight after quarantine ended in mid-2021.

\vspace{1cm}

10. Do male science teachers tend to receive higher salaries than female science teachers and, if so, how much higher are their salaries?  