---
title: "In-Class Worksheet"
author: "STAT011 with Prof Suzy"
date: 'Week 4: Designing a Statistical Study'
output:
  pdf_document: default
  html_document: default
---
\vspace{.5cm}
**Name:** _____________________________________

\vspace{1cm}
**Instructions:** There are two parts to this worksheet. First, work on the five questions in Part 1 by yourself. Then, when instructed by your professor, get into groups to discuss your answers to Part 1 and move on to complete Part 2. Before getting started however, take a moment and reflect on ways in which you can show your assigned group members respect. You may also view this initial [list of examples](https://docs.google.com/document/d/1emP8SiS2IO-_blKdVmVp-CJTr0NLlKG4vzMnphH-P7E/edit?usp=sharing) that we will add to over the semester.

**Briefly,** in the space below, specify one way in which you will work to show your group members respect during today's lesson:

\vspace{2cm}
```{r setup, echo=FALSE, include=FALSE}
require(knitr)
library(tidyverse)
knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings
```

# Part 1. Consider Random Sampling in Phone Surveys 

A sociologist plans to select $500$ names from the city phone book, call these numbers between noon and 4pm, and will interview whoever answers for their research project. The researcher anticipates contacting at least $200$ people. 

## 1.1) Why is it difficult to use a simple random sample here? 

\vspace{2cm}

## 1.2) What is a more convenient, but still random, sampling strategy? 

\pagebreak

## 1.3) What kinds of households are likely to be included/excluded in the eventual sample of opinions? 

\vspace{3cm}

## 1.4) Suppose the researcher decides to continue callinng each number, perhaps in the morning or evening, until an adult is contacted and interviewed. How does this improve the sampling design? 

\vspace{3cm}

## 1.5) Random-digit dialing machines can generate the phone calls for us. How would this improve the design of this sociologist's study? Is anyone still excluded? 

\vspace{3cm}

# Part 2. Design an Experiment for the Baseball Team 

It's generally believed that baseball players can hit the ball farther with aluminum bats than with the traditional wooden ones. Is this true? And if so, how much farther? 

Suppose Swarthmore's baseball team has agreed to help us answer these questions. Design an appropriate experiment.  

\vspace{5cm}