---
title: "In-Class Worksheet"
author: "STAT011 with Prof Suzy"
date: "Week 8: Probability and Random Variables"
output:
  html_document: default
---
<br>
**Name:** _____________________________________

<br>
**Instructions:** There are 3 parts to this worksheet. First, spend a few minutes thinking about your answers to Part 1. Then, when instructed by your professor, get into groups to finalize your answer to Part 1. Your instructor will tell you when to move on to Part 2 with your group. 


<!--Before getting started, take a moment and reflect on ways in which you can show your assigned group members respect. You may also view this initial [list of examples](https://docs.google.com/document/d/1emP8SiS2IO-_blKdVmVp-CJTr0NLlKG4vzMnphH-P7E/edit?usp=sharing) that we will add to over the semester.

**Briefly,** in the space below, specify one way in which you will work to show your group members respect during today's lesson:-->
<br>
<br>
<br>
<br>

```{r setup, echo=FALSE, include=FALSE}
require(knitr)
library(tidyverse)
knitr::opts_chunk$set(message = FALSE) # include this if you don't want markdown to knit messages
knitr::opts_chunk$set(warning = FALSE) # include this if you don't want markdown to knit warnings
```

# Part 1

**Instructions:** For Problems 1 and 2, consider the two probabilities given and consider the possible answers:

*	Probability (a) is greater than probability (b).

*	Probability (b) is greater than probability (a).

*	The two probabilities are equal.

*	It is impossible to tell. 

Explain which answer you think is most likely correct for each problem. 


## 1.  


(a) The probability that a randomly selected Swarthmore student wants to go to a statistics conference. 

(b) The probability that a randomly selected Swarthmore student wants to go to a statistics conference given they are a statistics major.


<br>
<br>
<br>
<br>

## 2.

(a) The probability that the cost of your flight is partially refunded and your luggage is lost. 

(b) The probability that the cost of your flights is partially refunded given that your luggage is lost. 


<br>
<br>
<br>
<br>


# Part 2

**Instructions:** Let's plan a trip. Suppose $8$ of us are going to travel to attend one of two international statistics conferences. (The rest of us are attending non-statistical conferences, naturally.) We need to request funding so we can travel to and from our destinations. Suppose $3$ of us are flying to Toronto, Canada for the 2023 Joint Statistical Meeting and $5$ of us are flying to the International Chinese Statistical Association conference in Chengdu, China.  

## 3. 

Suppose we pick a student from our class at random (in both sections combined there are $54$ students). Draw a tree diagram to show how to calculate the probability that this randomly selected student is going to a statistics conference and is traveling to Toronto this summer. 


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

# Part 3

**Instructions:** Airline ticket prices vary from time to time, but for simplicity, let's assume we're going to purchase all tickets for the same destination at the same price. Suppose also that past experience has shown that tickets to Toronto have a mean price of $\$563$, with a standard deviation of $\$70$, while the mean airfare to Chengdu is $\$5400$, with a standard deviation of $\$750$.

## 4. 

Define two random variables and use them to express the total amount of funding we will need to request to fly to both of these statistics conferences.

<br>
<br>
<br>
<br>



## 5. 


Find the mean and standard deviation of the total cost of the one-way-trip to our destinations. Do we need to make any assumptions in calculating these means or standard deviations?


<br>
<br>
<br>
<br>








 


